import { jsPDF } from 'jspdf';
import { formatMoney } from '../shared/helpers';

export default function generatePDF(tx) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('USC Procurement Department', pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('University of the Southern Caribbean', pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Invoice Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Invoice Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  doc.setFont('helvetica', 'bold');
  doc.text('Invoice Number:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(tx.invoice_number || '-', margin + 35, y);

  doc.setFont('helvetica', 'bold');
  doc.text('Date:', pageWidth / 2, y);
  doc.setFont('helvetica', 'normal');
  doc.text(tx.date || '-', pageWidth / 2 + 15, y);
  y += 7;

  doc.setFont('helvetica', 'bold');
  doc.text('Status:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(tx.status ? tx.status.charAt(0).toUpperCase() + tx.status.slice(1) : '-', margin + 18, y);
  y += 10;

  // Department Info
  doc.setFont('helvetica', 'bold');
  doc.text('Department:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(tx.account_name || '-', margin + 25, y);
  y += 7;

  doc.setFont('helvetica', 'bold');
  doc.text('Account Code:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(tx.account_code || '-', margin + 30, y);
  y += 12;

  // Line
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Table Header
  const colWidths = [70, 25, 35, 35];
  const colX = [margin, margin + colWidths[0], margin + colWidths[0] + colWidths[1], margin + colWidths[0] + colWidths[1] + colWidths[2]];

  doc.setFillColor(245, 241, 232);
  doc.rect(margin, y - 4, pageWidth - 2 * margin, 8, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Item', colX[0] + 2, y);
  doc.text('Qty', colX[1] + 2, y, { align: 'center' });
  doc.text('Unit Price', colX[2] + colWidths[2] - 2, y, { align: 'right' });
  doc.text('Total', colX[3] + colWidths[3] - 2, y, { align: 'right' });
  y += 8;

  // Table Rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  if (tx.items && tx.items.length > 0) {
    tx.items.forEach((item, idx) => {
      if (y > 260) {
        doc.addPage();
        y = margin;
      }

      doc.text(item.name || '-', colX[0] + 2, y);
      doc.text(String(item.quantity || 0), colX[1] + 2, y, { align: 'center' });
      doc.text(formatMoney(item.unitPrice), colX[2] + colWidths[2] - 2, y, { align: 'right' });
      doc.text(formatMoney(item.lineTotal), colX[3] + colWidths[3] - 2, y, { align: 'right' });
      y += 7;

      // Alternate row background
      if (idx % 2 === 0) {
        doc.setFillColor(250, 248, 243);
        doc.rect(margin, y - 11, pageWidth - 2 * margin, 7, 'F');
      }
    });
  } else {
    doc.text('No items', margin + 2, y);
    y += 7;
  }

  y += 4;
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Total
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Invoice Total:', pageWidth - margin - 50, y);
  doc.text(formatMoney(tx.invoice_total), pageWidth - margin - 2, y, { align: 'right' });
  y += 15;

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('This invoice was generated by the USC Procurement System', pageWidth / 2, y, { align: 'center' });
  y += 5;
  doc.text('Physical invoice book remains the official record of charge', pageWidth / 2, y, { align: 'center' });

  // Open PDF in new tab
  const pdfUrl = doc.output('bloburl');
  window.open(pdfUrl, '_blank');
}
