export const COST_CENTRES = [
  { code: 'ASACADE01', name: 'Office of the Provost' },
  { code: 'ASADVAN01', name: 'VP for Administration,Advancement & Planning' },
  { code: 'ASFINAD01', name: 'Financial Administration' },
  { code: 'ASPRESI01', name: "President's Office" },
  { code: 'ASSTUDE01', name: 'VP of Student Services & Enrollment Management' },
  { code: 'AUHUMAN01', name: 'Human Resources and Institutional Records' },
  { code: 'DPADMIS01', name: 'Admissions & Enrolment Management' },
  { code: 'DPALUMN01', name: 'Alumni' },
  { code: 'DPBUDEV01', name: 'Business Development' },
  { code: 'DPCAFET01', name: 'Cafeteria' },
  { code: 'DPCAMHE01', name: 'Campus Health Services' },
  { code: 'DPCOMMN01', name: 'Integrated Marketing & Communication (IMC)' },
  { code: 'DPCOMMU01', name: 'Commuter Dean' },
  { code: 'DPCOUNS01', name: 'Counselling' },
  { code: 'DPDEVEL01', name: 'Department of Business Development' },
  { code: 'DPEDITO01', name: 'Editorial' },
  { code: 'DPENGIN01', name: 'Planning&Engineering Service' },
  { code: 'DPFINAN01', name: 'Financial Affairs' },
  { code: 'DPGROUNDS01', name: 'Grounds Department' },
  { code: 'DPHEALT01', name: 'Health & Safety' },
  { code: 'DPHOUSE01', name: 'Houskeeping and Custodial' },
  { code: 'DPINFOR01', name: 'Information Technology' },
  { code: 'DPINREA01', name: 'Department of Institutional Research' },
  { code: 'DPINTER01', name: 'International Student Services' },
  { code: 'DPLADIE01', name: 'Ladies Residence Hall' },
  { code: 'DPLIBRA01', name: 'Library' },
  { code: 'DPMARKE01', name: 'Events and Hospitality' },
  { code: 'DPMOUNT01', name: 'Mountain View Residence Halls-Building # 1' },
  { code: 'DPPLANT01', name: 'Facilities Management' },
  { code: 'DPPROCU01', name: 'Procurement & Transportation' },
  { code: 'DPQUALI01', name: 'Quality Assurance' },
  { code: 'DPRECORDS01', name: 'Records Department' },
  { code: 'DPRELIG01', name: 'Spiritual Development' },
  { code: 'DPRESEA01', name: 'Research' },
  { code: 'DPSACEN01', name: 'Student Advisement Centre' },
  { code: 'DPSECUR01', name: 'Security' },
  { code: 'DPSPOR01', name: 'Sports & Physical Education' },
  { code: 'DPSTULI01', name: 'Student Life & Support Services' },
  { code: 'DPTIMGR01', name: 'Timothy Greaves Residence Hall' },
  { code: 'ISSBACC01', name: 'Accounting, Finance & Economics' },
  { code: 'ISSBMAR01', name: 'Marketing, Management & HR' },
  { code: 'ISSBMBA01', name: 'Graduate Department of Business' },
  { code: 'ISSBSCH01', name: 'School of Bus,Entreprenurship&Professional Studies' },
  { code: 'ISSEEDU01', name: 'Education' },
  { code: 'ISSEFAM01', name: 'Family & Consumer Science' },
  { code: 'ISSEGRA01', name: 'Graduate Department of Education' },
  { code: 'ISSESCH01', name: 'School of Education & Humanities' },
  { code: 'ISSHESL01', name: 'ESL' },
  { code: 'ISSHHIS01', name: 'History' },
  { code: 'ISSHINS01', name: "Int'l Center for Corporate Training&Language" },
  { code: 'ISSHLAN01', name: 'Language & Communication' },
  { code: 'ISSHMUS01', name: 'Music & Fine Arts' },
  { code: 'ISSRANT01', name: 'Antigua - Extension Campus' },
  { code: 'ISSRBAR01', name: 'Barbados - Extension Campus' },
  { code: 'ISSRDEA01', name: 'School of Distance Education' },
  { code: 'ISSRGRAD01', name: 'School of Graduate Studies' },
  { code: 'ISSRGUY01', name: 'Guyana - Extension Campus' },
  { code: 'ISSRPDI01', name: 'Professional Development Institute' },
  { code: 'ISSRSCH01', name: 'School of Theology & Religion' },
  { code: 'ISSRSOU01', name: 'South- Extension Campus' },
  { code: 'ISSRSTL01', name: 'St Lucia - Extension Campus' },
  { code: 'ISSRTOB01', name: 'Tobago- Extension Campus' },
  { code: 'ISSSBEH01', name: 'DEPARTMENT OF BEHAVIOURAL SCIENCES' },
  { code: 'ISSSGRA01', name: 'Graduate Department of Social Science' },
  { code: 'ISSSPYS01', name: 'Pyschology&Behavioral Sciences' },
  { code: 'ISSSSCH01', name: 'School of Social Sciences' },
  { code: 'ISSSSOC01', name: 'DO NOT USE!!Sociology' },
  { code: 'ISSSSOW01', name: 'Social Work' },
  { code: 'ISSTBIO01', name: 'Chemical & Biological Sciences' },
  { code: 'ISSTCOM01', name: 'Computing, Maths,Technology&Physical Science' },
  { code: 'ISSTNUR01', name: 'Nursing' },
  { code: 'ISSTOCC01', name: 'Graduate Department of Occupational Therapy' },
  { code: 'ISSTSCH01', name: 'School of Science & Technology' },
  { code: 'PSGENER01', name: 'General Services' },
  { code: 'SUBAKERY01', name: 'USC Bakery' },
  { code: 'SUBARBE01', name: 'USC Barber Shop' },
  { code: 'SUBOOKS01', name: 'USC Bookstore Plus' },
  { code: 'SUCAFE01', name: 'USC Cafe' },
  { code: 'SUEXTEN201', name: 'Mountain View Extension Dorm Building 2 Apt 1' },
  { code: 'SUEXTEN202', name: 'Mountain View Extension Dorm Building 2 Apt 2' },
  { code: 'SUEXTEN203', name: 'Mountain View Extension Dorm Building 2 Apt 3' },
  { code: 'SUEXTEN204', name: 'Mountain View Extension Dorm Building 2 Apt 4' },
  { code: 'SUEXTEN205', name: 'Mountain View Extension Dorm Building 2 Apt 5' },
  { code: 'SUEXTEN206', name: 'Mountain View Extension Dorm Building 2 Apt 6' },
  { code: 'SUEXTEN207', name: 'Mountain View Extension Dorm Building 2 Apt 7' },
  { code: 'SUFARM01', name: 'USC Farm' },
  { code: 'SUGROCE01', name: 'USC Grocery Store' },
  { code: 'SUGUEST01', name: 'Mountain View-Guest House' },
  { code: 'SULADIE01', name: 'Ladies Dorm Apt#1' },
  { code: 'SULAREA01', name: 'La Realista Guesthouse' },
  { code: 'SULYCEU01', name: 'Lyceum & Student Activities' },
  { code: 'SUMARI1001', name: 'Married Student Housing 10' },
  { code: 'SUMARI101', name: 'Married Student Housing 1' },
  { code: 'SUMARI1101', name: 'Married Student Housing 11' },
  { code: 'SUMARI1201', name: 'Married Student Housing 12' },
  { code: 'SUMARI201', name: 'Married Student Housing 2' },
  { code: 'SUMARI301', name: 'Married Student Housing 3' },
  { code: 'SUMARI401', name: 'Married Student Housing 4' },
  { code: 'SUMARI501', name: 'Married Student Housing 5' },
  { code: 'SUMARI601', name: 'Married Student Housing 6' },
  { code: 'SUMARI701', name: 'Married Student Housing 7' },
  { code: 'SUMARI801', name: 'Married Student Housing 8' },
  { code: 'SUMARI901', name: 'Married Student Housing 9' },
  { code: 'SUMARIE01', name: 'Married Student Complex-General' },
  { code: 'SUMOUNTA01', name: 'Mountain View Guest House Annex-Upper Level' },
  { code: 'SUMOUNTL01', name: 'Mountain View Apartment' },
  { code: 'SUMOUNTX01', name: 'Mountain View Guest House Annex-Lower Level' },
  { code: 'SURESI1001', name: 'Residence #10- Dr. Pilly Residence' },
  { code: 'SURESI101', name: 'Residence #1 - Dr. Mc Garrell Residence' },
  { code: 'SURESI1201', name: 'Residence #12- Old Health Service Building' },
  { code: 'SURESI301', name: 'Residence #3 - Ps. Spencer House' },
  { code: 'SURESI401', name: 'Residence #4- Dr. Lashley Residence/IAD House' },
  { code: 'SURESI501', name: 'Residence #5- Dr. Drepaul Residence' },
  { code: 'SURESI601', name: 'Residence #6 - Ps. Daniel Residence' },
  { code: 'SURESI701', name: 'Residence #7 - Ps. Beckles Residence' },
  { code: 'SURESI801', name: 'Residence #8-Opposite Gate 1-Upstairs Health Serv' },
  { code: 'SURESI901', name: 'Residence #9- Dr. Chesney Residence-Valley View' },
  { code: 'SUSNACK01', name: 'Snack Shop' },
  { code: 'SUSOUCA01', name: 'USC SOUTH CAMPUS CANTEEN' },
  { code: 'SUTHRIF01', name: 'USC THRIFT SHOP' },
  { code: 'SUTIMAPT101', name: 'Timothy Greaves Apt 1' },
  { code: 'SUTIMAPT201', name: 'Timothy Greaves Apt 2' },
  { code: 'SUTRANS01', name: 'USC-Transportation' },
  { code: 'SUWATER01', name: 'USC Water' },
]
